"""
Unit tests for GoogleAdapter - Google Gemini cloud inference.
Tests use mocks — no Google API key required.
"""

import pytest
from unittest.mock import AsyncMock, MagicMock, patch
from src.main.agent.adapters.google_adapter import GoogleAdapter
from src.main.agent.interfaces.llm_interface import LLMProvider
from src.main.agent.exceptions import LLMError, RateLimitError


class TestGoogleAdapter:

    @patch("src.main.agent.adapters.google_adapter.GoogleAdapter._init_llm")
    def test_default_model(self, mock_init):
        adapter = GoogleAdapter()
        assert adapter._model == "gemini-2.0-flash"

    @patch("src.main.agent.adapters.google_adapter.GoogleAdapter._init_llm")
    def test_provider_type(self, mock_init):
        adapter = GoogleAdapter()
        assert adapter.get_provider() == LLMProvider.GOOGLE

    @patch("src.main.agent.adapters.google_adapter.GoogleAdapter._init_llm")
    def test_context_window_1m(self, mock_init):
        adapter = GoogleAdapter(model="gemini-2.0-flash")
        assert adapter.get_context_window() == 1048576

    @patch("src.main.agent.adapters.google_adapter.GoogleAdapter._init_llm")
    def test_supports_function_calling(self, mock_init):
        adapter = GoogleAdapter()
        assert adapter.supports_function_calling() is True

    @patch("src.main.agent.adapters.google_adapter.GoogleAdapter._init_llm")
    def test_supports_vision(self, mock_init):
        adapter = GoogleAdapter()
        assert adapter.supports_vision() is True

    @pytest.mark.asyncio
    async def test_generate_success(self):
        with patch("src.main.agent.adapters.google_adapter.GoogleAdapter._init_llm"):
            adapter = GoogleAdapter()
            mock_resp = MagicMock()
            mock_resp.content = "generated by gemini"
            mock_resp.usage_metadata = {"input_tokens": 8, "output_tokens": 12, "total_tokens": 20}
            mock_resp.id = "gem-456"
            adapter._llm = AsyncMock()
            adapter._llm.ainvoke = AsyncMock(return_value=mock_resp)

            result = await adapter.generate("test")
            assert result["content"] == "generated by gemini"
            assert result["model"] == "gemini-2.0-flash"

    @pytest.mark.asyncio
    async def test_generate_quota_error(self):
        with patch("src.main.agent.adapters.google_adapter.GoogleAdapter._init_llm"):
            adapter = GoogleAdapter()
            adapter._llm = AsyncMock()
            adapter._llm.ainvoke = AsyncMock(side_effect=Exception("quota exceeded 429"))

            with pytest.raises(RateLimitError):
                await adapter.generate("test")
